export const instances = [
    {
      uuid: 10210,
      name: "myinstance",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },
    {
      uuid: 0,
      name: "apple",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },
    {
      uuid: 1,
      name: "ball",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },
    {
      uuid: 0,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },
    {
      uuid: 2,
      name: "cat",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },    {
      uuid: 3,
      name: "doll",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },
    {
      uuid: 4,
      name: "emblem",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },
    {
      uuid: 5,
      name: "fargate",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },    {
      uuid: 0,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },    {
      uuid: 0,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },    {
      uuid: 0,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },    {
      uuid: 0,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },    {
      uuid: 0,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },    {
      uuid: 0,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },    {
      uuid: 0,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },    {
      uuid: 0,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },    {
      uuid: 0,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },    {
      uuid: 0,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },    {
      uuid: 0,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 0,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 0,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },
    {
      uuid: 1,
      name: "string",
      ip: "string",
      desc: "string",
      creationDate: "2021-11-15T05:04:55.592Z",
      onlineInfo: [
        {
          startTime: 0,
          "period(ms)": 0,
        },
      ],
      securityGroup: {
        uuid: 1,
        name: "string",
        desc: "string",
        creationDate: "2021-11-15T05:04:55.592Z",
        defaultInboundPolicy: "drop",
        defaultOutboundPolicy: "drop",
        rules: [
          {
            uuid: 1,
            protocol: "string",
            ip: "0.0.0.0/0",
            port: 0,
            policy: "drop",
            desc: "string",
            trafficDirection: "inbound",
          },
        ],
        instances: ["string"],
      },
    },
  ];

  export const securityGroups = [
    
    {
      uuid: 10023,
      name: "rdp-sg",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 1002340,
      name: "email-client-sg",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 325230,
      name: "ssh-linux-sg",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 432345,
      name: "web-server-sg",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
    {
      uuid: 0,
      name: "string",
      desc: "string",
      creationDate: "2021-11-15T05:58:08.398Z",
      defaultInboundPolicy: "drop",
      defaultOutboundPolicy: "drop",
      rules: [
        {
          uuid: 0,
          protocol: "string",
          ip: "0.0.0.0/0",
          port: 0,
          policy: "drop",
          desc: "string",
          trafficDirection: "inbound",
        },
      ],
      instances: [
        {
          uuid: 0,
          name: "string",
          ip: "string",
          desc: "string",
          creationDate: "2021-11-15T05:58:08.398Z",
          onlineInfo: [
            {
              startTime: 0,
              "period(ms)": 0,
            },
          ],
          securityGroup: "string",
        },
      ],
    },
  ];
  